# Generated by Django 4.0.4 on 2022-04-22 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akins_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='brand',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='camera',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='megapixel',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
