# Generated by Django 4.0.4 on 2022-04-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akins_api', '0002_alter_drone_cameras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='cameras',
        ),
        migrations.AddField(
            model_name='drone',
            name='supported_cameras',
            field=models.ManyToManyField(to='akins_api.camera'),
        ),
    ]
