# Generated by Django 4.0.4 on 2022-04-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akins_api', '0003_remove_drone_cameras_drone_supported_cameras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='dimensions_folded',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='dimensions_unfolded',
        ),
    ]
