# Generated by Django 4.0.4 on 2022-04-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akins_api', '0004_remove_camera_dimensions_folded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='megapíxeles',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
