# Generated by Django 4.0.4 on 2022-04-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akins_api', '0005_alter_camera_megapíxeles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
