# Generated by Django 4.0.4 on 2022-04-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akins_api', '0006_rename_update_at_drone_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='video_resolution',
        ),
    ]
